### ISSUE TITLE
Experiment with Jetpack Compose in WhatTheStackActivity

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/WhatTheStack#12]
[Jetpack Compose](https://developer.android.com/jetpack/compose) is the next generation UI toolkit for Android. Creating an experimental version of the error screen in compose would serve as a nice playground for the project.

Tasks:
- Setup project for Jetpack Compose (enable compose in build features)
- Create an experimental version of `WhatTheStackActivity` using composables
- Incorporate Jetpack Compose's Material Theming for implementing dark mode support

**Comment by nsalazar0429** [comment]
I would like to work on this to try Jetpack Compose

**Comment by haroldadmin** [comment]
@cfsnsalazar That's great to hear.
For the initial switch I wanted to try to re-create the existing design of the `WhatTheStackActivity` in compose. A simple `Column` with a few style `Text` elements would be enough.

I am also open to other design ideas, so feel free to share yours.

**Comment by haroldadmin** [comment]
@cfsnsalazar Are you still working on this?

**Comment by HarisHoulis** [comment]
Hey @haroldadmin,
I am actively working on this and will be opening a PR in the next couple of hours.

**Comment by haroldadmin** [comment]
Thanks for taking this up @Charis1331 

Please make sure to raise the PR against the `dev` branch, not `master`. I don't want to include Compose related code in the stable releases, but it would be okay to do dev releases with it.

**Comment by haroldadmin** [comment]
Closing with #19
