### ISSUE TITLE
Add ability to restart the app from the error screen

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/WhatTheStack#14]
The crash screen should provide the user with the ability to restart the app.

Tasks:
- Record information to build an intent for the app when it crashes
- Add a button below _Share Stacktrace_ which fires the intent to launch the app again
- Finish the crashed activity

I am not sure how this would affect the task-stack. Might need to fiddle with launch options to fix unexpected behaviours.

**Comment by shivam21** [comment]
hi @haroldadmin I would like to work on this issue.Can I Raise the PR?

**Comment by haroldadmin** [comment]
Thank you for expressing your interest in the issue. Before you start working on it, it would be great to know your plan for fixing it.

**Comment by shivam21** [comment]
So the idea is to have a button below Share Stack trace.
Add a click listener on the button.
create launch intent to launch application again using packagemanager.
Clear the entire history stack and start the launcher activity using intent.

**Comment by haroldadmin** [comment]
Sounds good! I still have a small question though. Launching an application from the package manager requires you to know its package name. How do you plan on determining it?

**Comment by shivam21** [comment]
context.packageName will return application package name.

**Comment by haroldadmin** [comment]
Thanks for info. 

- I wanted to confirm if `context.packageName` returns the package name of the library, or of the application using it. I just checked and it does indeed return the package name of its application.
- You might want to include the `Intent.FLAG_ACTIVITY_CLEAR_TASK` to the intent to ensure that users can not go back to `WhatTheStackActivity` after starting the app.
- Lastly, please don't forget to add a proper icon to the restart button, just like the ones on "Copy Stacktrace" and "Share Stacktrace".

Assigning the issue to you now :)

**Comment by shivam21** [comment]
Does the ui looks good to you or please suggest from where should i get icon.
![WhatsApp Image 2020-10-03 at 11 15 39 AM](https://user-images.githubusercontent.com/17885414/94984467-dfd64a80-0569-11eb-8824-4d0522f29715.jpeg)

**Comment by haroldadmin** [comment]
Good work! I think this icon conveys the "restart" intention better: https://material.io/resources/icons/?search=refresh&icon=refresh&style=outline

**Comment by shivam21** [comment]
Thank you so much @haroldadmin.
Raised the PR please check.
