### ISSUE TITLE
Migrate to ViewBinding in the project

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/WhatTheStack#16]
WhatTheStack started as a small project to only display very basic information on a crash. `findViewById` sufficed for this purpose.

However, the complexity of the error screen has increased since then, and is going to continue in that direction. Therefore it makes sense to now refactor the project to migrate to [ViewBinding](https://developer.android.com/topic/libraries/view-binding) instead.

Tasks:
- Enable ViewBinding in the project's build configuration
- Migrate to ViewBinding in the sample app
- Migrate to ViewBinding in the library

**Comment by shivam21** [comment]
hi @haroldadmin 
any reason for not using kotlin synthetics?

**Comment by haroldadmin** [comment]
Yes. Kotlin Synthetics don't deal with view nullability in different configurations. They also don't work well for multi-module projects.

**Comment by shivam21** [comment]
thanks for the info.
would love to work on view bidings to know more.
@haroldadmin Can I work on this issue?

**Comment by haroldadmin** [comment]
Sure. Assigning it to you.

**Comment by shivam21** [comment]
Thanks @haroldadmin
 raised the PR Please check.
