### ISSUE TITLE
Support for targeting sdk 31

### ISSUE THREAD

**Issue by ldcomstock** [haroldadmin/WhatTheStack#26]
To support users of the library who are targeting SDK 12/S/31 or higher, please add `android:exported="true|false"` in `AndroidManifest.xml` for these components:

`com.haroldadmin.whatthestack.WhatTheStackService`
`com.haroldadmin.whatthestack.WhatTheStackActivity`
      
Currently the only way to get my app to build with `targetSdkVersion 31` is to add mergeable entries for these components in my app's Manifest with `android:exported="true"` to overwrite the library manifest entries i.e.

```
<service
          android:name="com.haroldadmin.whatthestack.WhatTheStackService"
          android:process=":what_the_stack_process"
          android:exported="false"
          tools:node="merge"/>
<activity
          android:name="com.haroldadmin.whatthestack.WhatTheStackActivity"
          android:process=":what_the_stack_process"
          android:exported="true"
          tools:node="merge"/>
```

see [https://developer.android.com/about/versions/12/behavior-changes-12#exported](https://developer.android.com/about/versions/12/behavior-changes-12#exported)

**Comment by haroldadmin** [comment]
I'm not sure if the issue applies to this library.

The documentation states that the `android:exported` attribute only needs to be added if your activity/service/broadcast-receiver has an intent filter, which is not the case with this library.

I tried to run the sample app in this repository with the following changes:
- Target SDK set to 31
- `android:exported=true` in the launcher activity of the sample app (not the library)
- No changes to the library manifest file

The app and the library worked correctly on API 31 emulator. 
I however did have to set `android:exported=true` on the sample app's launcher activity, but that shouldn't affect the library.

Could you either provide more details on your issue and/or a small sample project to reproduce this problem?

**Comment by haroldadmin** [comment]
[Release 1.0.0-alpha02](https://github.com/haroldadmin/WhatTheStack/releases/tag/1.0.0-alpha02) targets API 31. Please try that release to see if it fixes your issue. Closing this issue for now, feel free to reopen if the issue persists.
