### ISSUE TITLE
WhatTheStack does not capture very early crashes

### ISSUE THREAD

**Issue by matejdro** [haroldadmin/WhatTheStack#28]
For example, crash in MainActivity's `onCreate` method will not be captured.

**Comment by haroldadmin** [comment]
Duplicate of #3.

Unfortunately this is not an easily fixable problem. I would welcome ideas/fixes to resolve this though!

**Comment by haroldadmin** [comment]
Closing this issue in favour of #3. Let's keep the discussion in that thread.
