### ISSUE TITLE
Startup Crash IllegalStateException: Default FirebaseApp is not initialized in this process my.package.id:what_the_stack_process. Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by sebaslogen** [haroldadmin/WhatTheStack#6]
The app crashes on startup in the WTS process and I can't initialize the library manually without the content provider because it's annotated with an error and the initializer class is internal 😞

**Comment by haroldadmin** [comment]
Thanks for reporting this issue. I guessed issues were going to crop up with crash reporting libraries sooner or later, because WTS replaces the default uncaught exception handler 😅

I will try to take a look at this on the weekend, but until then can you share why manual initialization might help fix the issue?

**Comment by sebaslogen** [comment]
The Firebase crash is not very clear about which part of Firebase libs crashes but in the debug app we do `FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(false)`, so I thought initializing your lib after this line might resolve the problem.

**Comment by haroldadmin** [comment]
@sebaslogen I have been trying to reproduce this issue in the sample app of this repository, but I can't. Here are the steps I followed:

1. Created and integrated a firebase project with the sample app
2. Called `FirebaseCraslytics.getInstance().setCrashlyticsCollectionEnabled(false)` in the `onCreate` method of MainActivity
3. Pressed the "Crash!" button to cause a crash

I did not get the error you reported. The WhatTheStack screen showed up as usual.

Can you share more info about your project?

**Comment by sebaslogen** [comment]
We use different parts of the Firebase suite of products. Maybe Crashlytics is not the only reason, but another library linked to google services like Analytics or Messaging.

These are the firebase libs we use:
firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx:..."
firebaseCrashlytics = "com.google.firebase:firebase-crashlytics:..."
firebaseMessaging = "com.google.firebase:firebase-messaging:..."
firebaseRemoteConfig = "com.google.firebase:firebase-config-ktx:..."
firebasePerformanceMonitor = "com.google.firebase:firebase-perf:..."

**Comment by haroldadmin** [comment]
Thanks. I can not figure out why Firebase is even concerned with the process in which WhatTheStack's service runs. If possible, could you share a simple toy project to demonstrate this issue?

**Comment by sebaslogen** [comment]
It's a pity the crash could not be easily reproduced in the sample project.
Unfortunately, I don't have the time/means to produce a demo version of the closed source project where this crash happens, it's a very big project with a complex dynamic-feature modules setup.
Feel free to close this issue as can not reproduce.
